on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Build VSCode Web artifact
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up swap space
        run: |
          sudo fallocate -l 4G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile

      - name: Build VSCode Web
        run: make vscode-web-artifact

      - name: Upload Release Artifact
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.action_ref }}
          allowUpdates: true
          artifacts: "vscode-web*.zip"
